#!/usr/bin/env python3
import os
import re
import optparse
from xml.dom.minidom import parse


ns = "http://zero-install.sourceforge.net/2004/injector/interface"
zero2pypi_feed = "http://gfxmonk.net/dist/0install/zero2pypi.xml"

attrs = {}
name_extractor = re.compile('(?P<name>[^/.]+)(\.xml)?$')

def get_mapping():
	mapping = {}
	def read_mapping(filename):
		try:
			with open(filename) as f:
				lines = filter(None, map(lambda s: s.strip(), f.readlines()))
				for line in lines:
					k, v = line.split()
					mapping[k] = v
		except (IOError, OSError):
			pass
	read_mapping('.zero2pypi')
	read_mapping(os.path.expanduser('~/.zero2pypi'))
	return mapping

zero_to_pypi_package_mapping = get_mapping()

def extract_name_for_url(url):
	def get_translated(name):
		try:
			return zero_to_pypi_package_mapping[name]
		except KeyError: pass
	name = name_extractor.search(url).groupdict()['name']
	return get_translated(url) or get_translated(name) or name

def get_dependency_names(requirements):
	names = []
	for requirement in requirements:
		url = requirement.getAttribute('interface')
		name = extract_name_for_url(url)
		print("assuming http://pypi.python.org/pypi/%s for (%s)\n" % (name, url))
		version_specs = requirement.getElementsByTagNameNS(ns, "version") or []
		for version_spec in version_specs:
			not_before = version_spec.getAttribute("not-before")
			before = version_spec.getAttribute("before")
			if not_before:
				name = "%s>=%s" % (name, not_before)
			if before:
				name = "%s<%s" % (name, before)
		names.append(name)
	return names

def get_text(dom, nodename):
	elem = dom.getElementsByTagNameNS(ns, nodename)
	if elem:
		return str(elem[0].childNodes[0].data).strip()
	else:
		return None

def get_main_command(group):
	main_attr = group.getAttribute("main")
	if main_attr: return main_attr
	command_elements = group.getElementsByTagNameNS(ns, "command")
	main_commands = list(filter(lambda cmd: cmd.getAttribute("name") == 'run', command_elements))
	if main_commands:
		return main_commands[0].getAttribute('path')
	return None

def load_attrs(feed):
	attrs = {}
	with open(feed) as f:
		dom = parse(f)
	latest_group = dom.getElementsByTagNameNS(ns, "group")[-1]
	latest_implementation = latest_group.getElementsByTagNameNS(ns, "implementation")[-1]
	group_requires = latest_group.getElementsByTagNameNS(ns, "requires") or []
	implementation_requires = latest_implementation.getElementsByTagNameNS(ns, "requires") or []
	attrs['version'] = latest_implementation.getAttribute('version')

	uri = attrs['url'] = dom.documentElement.getAttribute("uri")
	name = attrs['name'] = os.path.splitext(os.path.basename(feed))[0]

	dependency_names = get_dependency_names(group_requires + implementation_requires)
	if dependency_names:
		attrs['install_requires'] = dependency_names
	
	main = get_main_command(latest_group)
	if main:
		if main.endswith(".py"):
			entry_point = ".".join((main[:-3].split(os.path.sep))) + ":main"
			print("assuming %s entry point for executable python script %s" % (entry_point, main))
			attrs['entry_points'] = {
				'console_scripts': ["%s=%s" % (name, entry_point)]
			}
		else:
			attrs['scripts'] = [main]


	summary = get_text(dom, "summary")
	if summary:
		attrs['description'] = summary

	description = get_text(dom, "description") or ""
	description = """
**Note**: This package has been built automatically by
`zero2pypi <{tool_uri}>`_.
If possible, you should use the zero-install feed instead:
{uri}

----------------

{description}
""".format(description=description, tool_uri=zero2pypi_feed, uri=uri)
	attrs['long_description'] = description
	make_string_values(attrs)
	return attrs

def make_string_values(d):
	for k,v in d.items():
		if isinstance(v, bytes):
			d[k] = v.decode('UTF-8')

def write_setup_py(attrs, filename):
	lines = ["\t%s=%s," % (k,repr(v)) for k,v in attrs.items()]
	result = """#!/usr/bin/env python

## NOTE: ##
## this setup.py was generated by zero2pypi:
## http://gfxmonk.net/dist/0install/zero2pypi.xml

from setuptools import *
setup(
	packages = find_packages(exclude=['test', 'test.*']),
%s
)
""" % ("\n".join(lines),)
	with open(filename, 'w') as setup:
		setup.write(result)

import stat
def chmod_x(filename):
	"""
	ensure file has all execute permissions
	(like chmod a+x <filename>)
	"""
	mode = os.stat(filename).st_mode
	os.chmod(filename, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

def main():
	p = optparse.OptionParser()
	opts, args = p.parse_args()
	feed_name, = args
	attrs = load_attrs(feed_name)
	dest = 'setup.py'
	write_setup_py(attrs, dest)
	chmod_x(dest)
	print("# Now run:\n./%s register" % (dest,))

if __name__ == '__main__':
	main()
